---

# R1:
#     hostname: "10.10.10.1"
#     groups:
#         - test_group1

# R2:
#     hostname: "10.10.10.2"
#     groups:
#         - test_group1

# R3:
#     hostname: "10.10.10.3"
#     groups:
#         - test_group2

R4:
    hostname: "sandbox-iosxr-1.cisco.com"
    groups:
        - sandbox
    data:
        ospf:
            ospf_rid: 1.1.1.1
            ospf_process: "1"
            ospf_networks:
                - ip: 10.10.10.10
                - wildcard: "0.0.0.255"
                - area: "0" 
                - ip: 10.10.20.10
                - wildcard: "0.0.0.255"
                - area: "1"
