---

R1:
    hostname: "10.10.10.1"
    groups:
        - test_group1

R2:
    hostname: "10.10.10.2"
    groups:
        - test_group1

R3:
    hostname: "10.10.10.3"
    groups:
        - test_group2

